require 'socket'
require 'etc'

module Coffle
	module TemplateMethods
		def automessage(comment="# ", width=80)
			time=Time.now.strftime("%Y-%m-%d %H:%M:%S %z")

			message=<<-end
This file was autogenerated from #{@entry.source} by #{username}@#{hostname} on #{time}. You should not make any changes here, as they may be overwritten when the file is regenerated.

To regenerate this file, execute the following command:
    #{$0} build
in the following directory:
    #{Dir.getwd}
end
			message.wrap(width-comment.length).prefix_lines(comment)
		end

		def username
			Etc.getlogin
		end

		def hostname
			Socket.gethostname
		end

		def host(*hosts)
			yield if hosts.include? hostname
		end

		def skip!
			@skipped=true
		end

		def skipped?
			@skipped
		end
	end
end


