require 'socket'

module Coffle
	module TemplateMethods
		def automessage(comment="# ", width=80)
			time=Time.now.strftime("%Y-%m-%d %H:%M:%S %z")

			# Note the extra indentation before the command, somehow the word
			# wrapping seems to mess up the indenting.
			message=<<-end
This file was autogenerated from #{@source} by #{username}@#{hostname} on #{time}. You should not make any changes here, as they might be overwritten when the file is regenerated.

To regenerate this file, execute the following command:
      #{$0} build
in the following directory:
	#{Dir.getwd}
end
			message.wrap(width-comment.length).prefix_lines(comment)
		end

		def username
			# TODO use Etc.getlogin
			ENV['USERNAME']
		end

		def hostname
			Socket.gethostname
		end

		def host(*hosts)
			yield if hosts.include? hostname
		end
	end
end


